schema_version: "1.0"
mcp_name: "Ukraine Law MCP"
jurisdiction: "UA"

sources:
  - name: "Legislation of Ukraine Portal"
    authority: "Verkhovna Rada of Ukraine"
    official_portal: "https://zakon.rada.gov.ua"
    retrieval_method: "HTML_SCRAPE"
    update_frequency: "unknown"
    license_or_terms:
      type: "government_terms"
      url: "https://zakon.rada.gov.ua/laws/main/index"
      summary: "Official legislative texts are published by the Parliament of Ukraine and are publicly accessible."
    coverage:
      scope: "Full corpus ingestion from the Verkhovna Rada legal portal type lists: Constitution (t216), Codes of Ukraine (t21), Codes (t124), and Laws of Ukraine (t1)."
      limitations: "Records are skipped when the official print page is unavailable, inaccessible, or cannot be parsed; such cases are logged during ingestion."
    languages:
      - "uk"
      - "en"
