schema_version: "1.0"
mcp_name: "Ukraine Law MCP"
jurisdiction: "UA"

sources:
  - name: "Legislation of Ukraine Portal"
    authority: "Verkhovna Rada of Ukraine"
    official_portal: "https://zakon.rada.gov.ua"
    retrieval_method: "HTML_SCRAPE"
    update_frequency: "unknown"
    license_or_terms:
      type: "government_terms"
      url: "https://zakon.rada.gov.ua/laws/main/index"
      summary: "Official legislative texts are published by the Parliament of Ukraine and are publicly accessible."
    coverage:
      scope: "Current statutes and codes published in the Verkhovna Rada legal portal, including the 10 cyber/data-focused laws in this MCP."
      limitations: "This MCP currently ingests a selected subset of laws, not the full corpus."
    languages:
      - "uk"
      - "en"
